name: Bug Report
description: Report an issue with the website
title: "[Bug] <short summary>"
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the issue...
    validations:
      required: true
